name: Run Modified Solutions on Full Set

on:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        pack: ["ch2-S-50", "ch2-S-1000", "ch2-L-100", "ch2-L-5000", "ch2-XL-10000"]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies, fetch tags
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git fetch --all --tags
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-central-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Run Evaluation
      run: |
        inv test-modified-solutions --input-id ${{ matrix.pack }}
  retag:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [main]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Re-Tag
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git fetch --all --tags
        inv retag
